version: '3.8'

services:
  admin-service:
    container_name: admin_service 
    build: ./
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    volumes:
      - files_volume:/files

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - mynetwork
      
networks:
  mynetwork:
    external: true
    name: global-net

volumes:
  files_volume:
