version: '3.8'

services:
  admin-service:
    container_name: admin_service 
    build: ./
    ports:
      - "8080:8080"
    networks:
      - mynetwork


networks:
  mynetwork:
    external: true
    name: global-net
    

volumes:
  db: