version: '3.8'

services:
  user-service:
    container_name: user_service 
    build: ./
    ports:
      - "8081:8081"
    networks:
      - mynetwork  

networks:
  mynetwork:
    external: true
    name: global-net
    

volumes:
  db:
  redis-data: