name: Web Polling Service 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Check out the repository
    - name: Checkout our repository
      uses: actions/checkout@v4

    # Step 2: Deploy the application
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "---------------- PULLING CODE FROM GITHUB ----------------"
          cd web-poll
          git pull origin main
          echo "---------------- CODE PULLED FROM GITHUB -----------------"

          echo "---------------- NAVIGATING TO POLLING DIRECTORY ----------------"
          cd polling
          
          sudo docker compose down
          echo "---------------- POLLING SERVICES STOPPED ----------------"
          
          sudo docker compose up --build -d
          echo "---------------- POLLING SERVICES STARTED ----------------"

          echo "---------------- NAVIGATING TO API-GATEWAY DIRECTORY ----------------"
          cd ../api-gateway
          
          sudo docker compose down
          echo "---------------- API-GATEWAY SERVICES STOPPED ----------------"
          
          sudo docker compose up --build -d
          echo "---------------- API-GATEWAY SERVICES STARTED ----------------"